spring.application.name=market-map-backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/market_map}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:market_map}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:market_map}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
